#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Select samples by rich predicates from features.parquet and export to JSONL (sorted by step).

Key features
- Validate source JSONL unchanged (size/mtime; sha256 if meta recorded).
- Filters:
  --kept-or-dropped {all,kept,dropped}
  --cls {any,correct,wrong,no_judge}
  --step-min / --step-max
  --chinese-or-english {all,chinese,english}
  --where 'pandas-like expression'  (e.g., 'non_ascii_ratio>0.15 or top1_word_prop>0.3')
  --ge/--le/--eq 'col:val' repeated options (AND by default; use --logic or)
  --dedup-uid
  --limit / --per-step-limit
- Export:
  --keys all               : byte-precise copy of raw lines (no parse, fastest), selector parses each selected raw line, merges a text_metrics object (all text metrics columns), and writes a single enriched JSON per line.
  --keys k1,k2,k3          : if builder snapshotted, use snapshot columns (no parse). Otherwise parse only selected rows.
  --with-core-keys         : include {global_step,uid,line_no} implicitly for keys!=all (default on)
- Sort:
  default by (global_step asc, byte_offset asc). Override via --sort-by 'col1:asc,col2:desc'

NOTE: Requires the out-dir generated by build_features_from_jsonl.py.
"""

from __future__ import annotations
from pathlib import Path
import argparse, json, os, sys, time, math, re
from typing import Any, Dict, List, Tuple, Optional
import numpy as np
import pandas as pd

try:
    import orjson
    def _json_loads(b: bytes):
        return orjson.loads(b)
    def _json_dumps(obj: Any) -> bytes:
        return orjson.dumps(obj, option=orjson.OPT_SERIALIZE_NUMPY)
except Exception:
    import json as _json
    def _json_loads(b: bytes):
        return _json.loads(b.decode("utf-8", errors="replace"))
    def _json_dumps(obj: Any) -> bytes:
        return (_json.dumps(obj, ensure_ascii=False) + "\n").encode("utf-8")

# === Text metric columns computed by builder (must match build_features_from_jsonl.py) ===
TEXT_METRIC_COLS = [
    "resp_char_len",
    "resp_byte_len",
    "non_ascii_ratio",
    "replacement_char_ratio",
    "control_private_unassigned_ratio",
    "repeat_char_run_max",
    "repeat_word_run_max",
    "unique_word_ratio",
    "top1_word_prop",
    "trigram_repeat_ratio",
    "compress_ratio",
    "char_entropy_bits_per_char",
]

def _num_or_none(x):
    """Convert numpy/pandas numbers to plain float; NaN/Inf -> None (valid JSON)."""
    try:
        if x is None:
            return None
        # pandas NA / numpy NaN
        import math
        if isinstance(x, (float, np.floating)):
            if not math.isfinite(float(x)):
                return None
            return float(x)
        if isinstance(x, (int, np.integer)):
            return int(x)
        # other types (e.g., strings) pass through
        return x
    except Exception:
        return None

def put_nested(dst: Dict[str, Any], path: str, value: Any):
    cur = dst
    parts = path.split(".")
    for p in parts[:-1]:
        if p not in cur or not isinstance(cur[p], dict):
            cur[p] = {}
        cur = cur[p]
    cur[parts[-1]] = value

def parse_cmp_list(items: List[str]) -> List[Tuple[str, float]]:
    out = []
    for it in items or []:
        if ":" not in it:
            raise ValueError(f"Bad 'col:val' item: {it}")
        col, val = it.split(":", 1)
        out.append((col.strip(), float(val)))
    return out

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", type=Path, required=True,
                    help="Directory produced by builder (must contain meta.json & features.parquet).")
    ap.add_argument("--out-jsonl", type=Path, required=True)
    ap.add_argument("--kept-or-dropped", type=str, default="all", choices=["all","kept","dropped"])
    ap.add_argument("--cls", type=str, default="any", choices=["any","correct","wrong","no_judge"])
    ap.add_argument("--chinese-or-english", type=str, default="all",
                    choices=["all","chinese","english"],
                    help="Language filter based on builder's contain_chinese (1:chinese, 0:english, -1:unknown).")
    ap.add_argument("--step-min", type=int, default=None)
    ap.add_argument("--step-max", type=int, default=None)
    ap.add_argument("--where", type=str, default=None,
                    help="Pandas query expression, e.g., 'non_ascii_ratio>0.15 or top1_word_prop>0.3'")
    ap.add_argument("--ge", action="append", default=[], help="threshold: 'col:val' (>=)")
    ap.add_argument("--le", action="append", default=[], help="threshold: 'col:val' (<=)")
    ap.add_argument("--eq", action="append", default=[], help="threshold: 'col:val' (==)")
    ap.add_argument("--logic", type=str, default="and", choices=["and","or"],
                    help="Combine --ge/--le/--eq conditions with AND or OR")
    ap.add_argument("--dedup-uid", action="store_true")
    ap.add_argument("--limit", type=int, default=None)
    ap.add_argument("--per-step-limit", type=int, default=None)
    ap.add_argument("--keys", type=str, default="all",
                    help="'all' or comma list of dot-keys to export")
    ap.add_argument("--with-core-keys", action="store_true", default=True,
                    help="Include {global_step,uid,line_no} when keys!=all (default true)")
    ap.add_argument("--sort-by", type=str, default="global_step:asc,byte_offset:asc")
    args = ap.parse_args()

    meta_path = args.out_dir / "meta.json"
    feat_path = args.out_dir / "features.parquet"
    if not meta_path.exists() or not feat_path.exists():
        raise FileNotFoundError("meta.json or features.parquet not found in --out-dir")

    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    src = Path(meta["source_jsonl"])
    if not src.exists():
        raise FileNotFoundError(f"source jsonl not found: {src}")

    # validate file unchanged
    st = src.stat()
    if st.st_size != meta["source_size"] or int(st.st_mtime) != meta["source_mtime"]:
        print("[WARN] Source JSONL size/mtime changed since build; consider rebuild.", file=sys.stderr)
    if meta.get("source_sha256"):
        # optional strict check
        print("[INFO] meta includes sha256; verifying (slow) ...")
        import hashlib
        h = hashlib.sha256()
        with src.open("rb", buffering=1024*1024) as f:
            for chunk in iter(lambda: f.read(1024*1024), b""):
                h.update(chunk)
        if h.hexdigest() != meta["source_sha256"]:
            print("[WARN] sha256 mismatch; selector will still proceed, but results may be inconsistent.", file=sys.stderr)

    print(f"[INFO] Loading features: {feat_path}")
    # Columns we always need for exporting/sorting
    base_cols = ["line_no","byte_offset","byte_len","global_step","uid","kept_flag","cls_id"]
    df = pd.read_parquet(feat_path, columns=None)  # load all; typically few hundred MB
    for c in base_cols:
        if c not in df.columns:
            raise KeyError(f"Missing required column in features: {c}")

    # Filtering
    mask = np.ones(len(df), dtype=bool)
    if args.kept_or_dropped == "kept":
        mask &= (df["kept_flag"] == 1)
    elif args.kept_or_dropped == "dropped":
        mask &= (df["kept_flag"] == 0)

    if args.cls != "any":
        cls_map = {"correct":1, "wrong":0, "no_judge":2}
        mask &= (df["cls_id"] == cls_map[args.cls])

    if args.step_min is not None:
        mask &= (df["global_step"] >= int(args.step_min))
    if args.step_max is not None:
        mask &= (df["global_step"] <= int(args.step_max))
    # language filter based on contain_chinese
    if args.chinese_or_english != "all":
        if "contain_chinese" not in df.columns:
            print("[ERROR] 'contain_chinese' column not found in features. "
                  "Please rebuild features with the updated builder.", file=sys.stderr)
            sys.exit(2)
        if args.chinese_or_english == "chinese":
            mask &= (df["contain_chinese"] == 1)
        elif args.chinese_or_english == "english":
            mask &= (df["contain_chinese"] == 0)

    # thresholds
    ge_list = parse_cmp_list(args.ge)
    le_list = parse_cmp_list(args.le)
    eq_list = parse_cmp_list(args.eq)
    if ge_list or le_list or eq_list:
        cur = np.zeros(len(df), dtype=bool) if args.logic == "or" else np.ones(len(df), dtype=bool)
        def comb(cur, cond):
            return (cur | cond) if args.logic == "or" else (cur & cond)
        for col, val in ge_list:
            if col not in df.columns: raise KeyError(f"--ge: unknown column {col}")
            cond = (df[col].astype(float) >= float(val))
            cur = comb(cur, cond.values)
        for col, val in le_list:
            if col not in df.columns: raise KeyError(f"--le: unknown column {col}")
            cond = (df[col].astype(float) <= float(val))
            cur = comb(cur, cond.values)
        for col, val in eq_list:
            if col not in df.columns: raise KeyError(f"--eq: unknown column {col}")
            cond = (df[col].astype(float) == float(val))
            cur = comb(cur, cond.values)
        mask &= cur

    if args.where:
        try:
            mask &= df.query(args.where, engine="python").index.to_series().reindex(df.index, fill_value=False).values
        except Exception as e:
            print(f"[ERROR] Failed to evaluate --where: {e}", file=sys.stderr)
            sys.exit(2)

    sel = df[mask].copy()
    if args.dedup_uid and "uid" in sel.columns:
        sel = sel.sort_values(["global_step","byte_offset"], kind="mergesort").drop_duplicates("uid", keep="first")

    # per-step limit
    if args.per_step_limit is not None and args.per_step_limit > 0:
        sel = (sel.sort_values(["global_step","byte_offset"], kind="mergesort")
                  .groupby("global_step", sort=False)
                  .head(int(args.per_step_limit))
                  .reset_index(drop=True))

    # sorting
    sort_spec = []
    for seg in (args.sort_by or "").split(","):
        seg = seg.strip()
        if not seg: continue
        if ":" in seg:
            col, od = seg.split(":", 1)
            sort_spec.append( (col.strip(), od.strip().lower()!="desc") )
        else:
            sort_spec.append( (seg, True) )
    if not sort_spec:
        sort_spec = [("global_step", True), ("byte_offset", True)]
    sel = sel.sort_values([c for c,_ in sort_spec], ascending=[a for _,a in sort_spec], kind="mergesort")

    if args.limit is not None and args.limit > 0:
        sel = sel.head(int(args.limit))

    print(f"[INFO] Selected rows: {len(sel):,}")

    keys_arg = args.keys.strip()
    # if keys_arg == "all":
    #     # zero-parse fast path: copy raw bytes by offset
    #     outp = args.out_jsonl
    #     outp.parent.mkdir(parents=True, exist_ok=True)
    #     with src.open("rb", buffering=1024*1024) as fsrc, outp.open("wb") as fdst:
    #         for _, row in sel.iterrows():
    #             off = int(row.byte_offset); ln = int(row.byte_len)
    #             b = os.pread(fsrc.fileno(), ln, off)
    #             # Ensure newline: original line already includes trailing '\n' (as we measured len)
    #             fdst.write(b)
    #     print(f"[SAVED] {outp} (raw copy, keys=all)")
    #     return
    if keys_arg == "all":
        # Parse each selected line, merge text_metrics from features row, and dump enriched JSON.
        outp = args.out_jsonl
        outp.parent.mkdir(parents=True, exist_ok=True)

        # We keep a map of which metric columns actually exist (robust to future schema changes)
        avail_metrics = [c for c in TEXT_METRIC_COLS if c in sel.columns]
        if len(avail_metrics) < len(TEXT_METRIC_COLS):
            missing = [c for c in TEXT_METRIC_COLS if c not in sel.columns]
            if missing:
                print(f"[WARN] Some text metric columns not found in features: {missing}", file=sys.stderr)

        with src.open("rb", buffering=1024*1024) as fsrc, outp.open("wb") as fdst:
            for _, row in sel.iterrows():
                off = int(row.byte_offset); ln = int(row.byte_len)
                b = os.pread(fsrc.fileno(), ln, off)

                # Try parse original JSON
                try:
                    obj = _json_loads(b)
                    if not isinstance(obj, dict):
                        raise ValueError("not a dict")
                    parse_ok = True
                except Exception:
                    # extremely rare; keep raw line (decoded) and mark parse error
                    try:
                        raw_line = b.decode("utf-8", errors="replace").rstrip("\n")
                    except Exception:
                        raw_line = ""
                    obj = {
                        "_parse_error": True,
                        "_raw_line": raw_line,
                    }
                    parse_ok = False

                # Build text_metrics from feature columns (NaN/Inf -> null)
                tm = {}
                for col in avail_metrics:
                    tm[col] = _num_or_none(row[col])

                # Merge
                obj["text_metrics"] = tm

                # (Optional) also attach minimal selection/core info to help traceability
                # You may comment these 3 lines if you don't want duplicates of existing fields.
                obj.setdefault("global_step", int(row["global_step"]))
                obj.setdefault("uid", row["uid"])
                obj.setdefault("line_no", int(row["line_no"]))

                # Dump one enriched JSON line
                line = _json_dumps(obj)
                if isinstance(line, bytes):
                    fdst.write(line + (b"" if line.endswith(b"\n") else b"\n"))
                else:
                    fdst.write((line if line.endswith("\n") else line + "\n").encode("utf-8"))

        print(f"[SAVED] {outp} (enriched copy, keys=all + text_metrics)")
        return

    # keys list mode
    req_keys = [k.strip() for k in keys_arg.split(",") if k.strip()]
    snap_map: Dict[str,str] = meta.get("snapshot_columns", {})
    snap_cols_to_use = {}   # key -> colname in features
    parse_keys = []         # keys not snapshotted -> need parse

    for k in req_keys:
        col = snap_map.get(k)
        if col and col in sel.columns:
            snap_cols_to_use[k] = col
        else:
            parse_keys.append(k)

    # always include core keys?
    core_keys = []
    if args.with_core_keys:
        core_keys = ["global_step","uid","line_no"]

    # pre-open src for selective parsing when needed
    fd = os.open(str(src), os.O_RDONLY)

    outp = args.out_jsonl
    outp.parent.mkdir(parents=True, exist_ok=True)
    with outp.open("wb") as fo:
        for _, row in sel.iterrows():
            if not parse_keys:
                # fully covered by snapshots
                obj: Dict[str, Any] = {}
                for k in core_keys:
                    obj[k] = row[k]
                for k, col in snap_cols_to_use.items():
                    put_nested(obj, k, row[col])
                # dump
                line = _json_dumps(obj)
                if isinstance(line, bytes):
                    fo.write(line + (b"" if line.endswith(b"\n") else b"\n"))
                else:
                    fo.write((line if line.endswith("\n") else line+"\n").encode("utf-8"))
            else:
                # need to parse this line from source
                off = int(row.byte_offset); ln = int(row.byte_len)
                b = os.pread(fd, ln, off)
                try:
                    obj_src = _json_loads(b)
                except Exception:
                    obj_src = {}

                obj_out: Dict[str, Any] = {}
                for k in core_keys:
                    # prefer from features for consistency
                    obj_out[k] = row[k]

                # snapshots
                for k, col in snap_cols_to_use.items():
                    put_nested(obj_out, k, row[col])

                # parse-only keys
                for k in parse_keys:
                    # nested path extraction
                    cur = obj_src
                    for p in k.split("."):
                        if isinstance(cur, dict) and p in cur:
                            cur = cur[p]
                        else:
                            cur = None
                            break
                    put_nested(obj_out, k, cur)

                line = _json_dumps(obj_out)
                if isinstance(line, bytes):
                    fo.write(line + (b"" if line.endswith(b"\n") else b"\n"))
                else:
                    fo.write((line if line.endswith("\n") else line+"\n").encode("utf-8"))

    os.close(fd)
    print(f"[SAVED] {outp} (keys={req_keys}, snapshots_used={list(snap_cols_to_use.keys())}, parsed_keys={parse_keys})")

if __name__ == "__main__":
    main()
