#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_features_embedding.py

Stage 2: 从 Stage1 生成的 segments.parquet 中读取 sentence 文本，使用多语言 embedding 模型（如 BAAI/bge-m3）
在 GPU 上批量计算 embedding，写出 sentence_embeddings.parquet。

- 不做任何聚类/分析，只负责“把字符串 -> 向量”这一步。
- 保证输出与 segments.parquet 在行数和顺序上严格对齐（每行一个 embedding，对应一个 sentence）。
"""

from __future__ import annotations
from pathlib import Path
import argparse, os, sys, time
from typing import List

import numpy as np
import pandas as pd
import json

import torch
from transformers import AutoTokenizer, AutoModel

import pyarrow as pa
import pyarrow.parquet as pq

def encode_batch(model, tokenizer, texts: List[str], device: torch.device, max_length: int) -> np.ndarray:
    """
    对一个 batch 的句子做 embedding.
    使用典型 BGE-style mean pooling + L2 normalize.
    返回 np.ndarray[batch, hidden_size].
    """
    if not texts:
        return np.zeros((0, 1), dtype=np.float32)

    enc = tokenizer(
        texts,
        padding=True,
        truncation=True,
        max_length=max_length,
        return_tensors="pt"
    )
    for k in enc:
        enc[k] = enc[k].to(device)

    with torch.no_grad():
        out = model(**enc)
        # last_hidden_state [B, T, H]
        last_hidden = out.last_hidden_state
        mask = enc["attention_mask"].unsqueeze(-1)  # [B, T, 1]
        masked = last_hidden * mask
        sum_hidden = masked.sum(dim=1)                       # [B, H]
        lengths = mask.sum(dim=1).clamp(min=1)               # [B, 1]
        mean_pooled = sum_hidden / lengths
        # L2 normalize
        mean_pooled = torch.nn.functional.normalize(mean_pooled, p=2, dim=1)

    return mean_pooled.cpu().numpy().astype(np.float32)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--segments-parquet", type=Path, required=True,
                    help="Path to segments.parquet generated by build_features_preprocess.py")
    ap.add_argument("--out-dir", type=Path, required=True)
    ap.add_argument("--model-name", type=str, default="BAAI/bge-m3")
    ap.add_argument("--device", type=str, default="cuda",
                    help="e.g., 'cuda', 'cuda:0', or 'cpu'")
    ap.add_argument("--batch-size", type=int, default=64)
    ap.add_argument("--max-length", type=int, default=512,
                    help="Max sequence length for the embedding model")
    ap.add_argument("--max-segments", type=int, default=-1,
                    help="For debugging: limit total number of sentences to encode (-1 = no limit)")
    args = ap.parse_args()

    segments_path = args.segments_parquet
    out_dir = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    emb_path = out_dir / "sentence_embeddings.parquet"
    meta_path = out_dir / "meta_embedding.json"

    device = torch.device(args.device if torch.cuda.is_available() or "cpu" not in args.device else "cpu")
    print(f"[Stage2] Loading embedding model '{args.model-name}' on device {device} ...")
    t0 = time.time()
    tokenizer = AutoTokenizer.from_pretrained(args.model_name, trust_remote_code=True)
    model = AutoModel.from_pretrained(args.model_name, trust_remote_code=True)
    model.to(device)
    model.eval()
    torch.set_grad_enabled(False)
    print(f"[Stage2] Model loaded in {time.time()-t0:.1f}s")

    pf = pq.ParquetFile(str(segments_path))
    num_row_groups = pf.num_row_groups
    print(f"[Stage2] segments.parquet has {num_row_groups} row groups")

    writer = None
    n_rows_total = 0
    n_rows_encoded = 0
    t1 = time.time()

    for rg_idx in range(num_row_groups):
        print(f"[Stage2] Reading row group {rg_idx+1}/{num_row_groups} ...")
        table = pf.read_row_group(rg_idx)
        df = table.to_pandas()
        n_rows = len(df)
        n_rows_total += n_rows

        texts = df["text"].astype(str).tolist()
        embs_list: List[List[float]] = [None] * n_rows  # type: ignore

        # 按 batch 做 embedding
        start = 0
        while start < n_rows:
            if args.max_segments > 0 and n_rows_encoded >= args.max_segments:
                break
            end = min(start + args.batch_size, n_rows)
            batch_texts = texts[start:end]
            # 对于极短/空句子，可以直接给零向量，避免浪费
            mask_nonempty = [len(t.strip()) > 0 for t in batch_texts]
            if any(mask_nonempty):
                texts_to_encode = [t for t, m in zip(batch_texts, mask_nonempty) if m]
                emb_batch = encode_batch(model, tokenizer, texts_to_encode, device, args.max_length)
                ptr = 0
                for idx_local, m in enumerate(mask_nonempty):
                    idx_global = start + idx_local
                    if not m:
                        # 空句子：使用 None，占位
                        embs_list[idx_global] = None  # type: ignore
                    else:
                        vec = emb_batch[ptr]
                        embs_list[idx_global] = vec.tolist()  # type: ignore
                        ptr += 1
                        n_rows_encoded += 1
            else:
                # 全是空句子
                for idx_local in range(end-start):
                    embs_list[start + idx_local] = None  # type: ignore

            start = end

            if args.max_segments > 0 and n_rows_encoded >= args.max_segments:
                print(f"[Stage2] Hit max_segments={args.max_segments}, stop encoding further rows.")
                break

        df_out = pd.DataFrame({
            "sample_idx": df["sample_idx"].astype(np.int64),
            "section_idx": df["section_idx"].astype(np.int32),
            "sent_idx": df["sent_idx"].astype(np.int32),
            "emb": embs_list,
        })

        table_out = pa.Table.from_pandas(df_out, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(str(emb_path), table_out.schema, compression="zstd", version="2.6")
        writer.write_table(table_out)

        print(f"  [Stage2] row_group={rg_idx+1}, rows={n_rows}, encoded={n_rows_encoded}, total_rows={n_rows_total}")

        if args.max_segments > 0 and n_rows_encoded >= args.max_segments:
            break

    if writer is not None:
        writer.close()

    print(f"[Stage2] Wrote embeddings: {emb_path}")
    print(f"[Stage2] Total rows={n_rows_total}, encoded_segments={n_rows_encoded}, time={time.time()-t1:.1f}s")

    meta = {
        "segments_path": str(segments_path),
        "embeddings_path": str(emb_path),
        "model_name": args.model_name,
        "device": str(device),
        "batch_size": args.batch_size,
        "max_length": args.max_length,
        "rows_total": n_rows_total,
        "rows_encoded": n_rows_encoded,
        "build_time_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    with meta_path.open("w", encoding="utf-8") as f:
        json.dump(meta, f, ensure_ascii=False, indent=2)
    print(f"[Stage2] Wrote meta: {meta_path}")

if __name__ == "__main__":
    main()
