#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_features_embedding.py  (Stage 2, vLLM backend)

从 Stage1 生成的 segments.parquet 中读取 sentence 文本，
使用 vLLM 的 LLM(task="embed") 一次性把每个 row-group 的所有句子
塞进 vLLM 的 embed()，让 vLLM 自己做 batching / 调度。

输出:
  - sentence_embeddings.parquet: 每个 sentence 一行
      columns: [sample_idx, section_idx, sent_idx, emb]
"""

from __future__ import annotations
from pathlib import Path
import argparse, os, time, json
from typing import List, Any

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

from vllm import LLM  # vLLM 离线推理 API  :contentReference[oaicite:1]{index=1}
from tqdm.auto import tqdm  # 新增：进度条

def extract_embedding_from_output(output: Any) -> List[float]:
    """
    vLLM embed() 的每个返回元素是 EmbeddingRequestOutput：
      - output.outputs 可能是 PoolingOutput 或 [PoolingOutput]
      - PoolingOutput.embedding 已经封装为 list[float]（兼容旧 API）:contentReference[oaicite:2]{index=2}
      - 或者可以用 .data.tolist()
    做一个稍微鲁棒一点的抽取。
    """
    outs = getattr(output, "outputs", None)
    if outs is None:
        return []

    # 可能是单个 PoolingOutput
    if hasattr(outs, "embedding"):
        try:
            return list(outs.embedding)
        except Exception:
            pass
    if hasattr(outs, "data"):
        try:
            return outs.data.tolist()
        except Exception:
            pass

    # 可能是 list[PoolingOutput]
    if isinstance(outs, (list, tuple)) and len(outs) > 0:
        o0 = outs[0]
        if hasattr(o0, "embedding"):
            try:
                return list(o0.embedding)
            except Exception:
                pass
        if hasattr(o0, "data"):
            try:
                return o0.data.tolist()
            except Exception:
                pass

    # 实在拿不到，就返回空
    return []


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--segments-parquet", type=Path, required=True,
                    help="Path to segments.parquet generated by build_features_preprocess.py")
    ap.add_argument("--out-dir", type=Path, required=True,
                    help="Output directory, sentence_embeddings.parquet will be written here")
    ap.add_argument("--model-name", type=str, default="BAAI/bge-m3",
                    help="Embedding model name/path supported by vLLM (e.g., BAAI/bge-m3, nomic-ai/nomic-embed-text-v1.5)")
    ap.add_argument("--tensor-parallel-size", type=int, default=1,
                    help="Number of GPUs for tensor parallelism in vLLM")
    ap.add_argument("--dtype", type=str, default="auto",
                    help="Model dtype for vLLM: auto/float16/bfloat16/float32 等，具体取决于 vLLM 版本")
    ap.add_argument("--gpu-memory-utilization", type=float, default=0.9,
                    help="vLLM gpu_memory_utilization，0~1，越大 KV cache 越大，但可能 OOM:contentReference[oaicite:3]{index=3}")
    ap.add_argument("--trust-remote-code", action="store_true",
                    help="Pass trust_remote_code=True to vLLM.LLM (for models with custom code)")
    ap.add_argument("--enforce-eager", action="store_true",
                    help="Use enforce_eager=True in LLM to禁用 CUDA graph，调试/小 batch 时更稳定:contentReference[oaicite:4]{index=4}")
    ap.add_argument("--max-segments", type=int, default=-1,
                    help="(可选 debug) 只对前 N 个 sentence 做 embedding，-1 表示全部。"
                         "注意：如果用这个截断，Stage3 也需要用子集，否则行数对不上。")
    args = ap.parse_args()

    segments_path = args.segments_parquet
    out_dir = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    emb_path = out_dir / "sentence_embeddings.parquet"
    meta_path = out_dir / "meta_embedding.json"

    # ---- 初始化 vLLM 引擎 ----
    # vLLM 会自动做连续 batching；encode/embed 都会根据 GPU 内存自动切 batch，
    # 文档推荐“把所有 prompts 放进一个 list 里交给它”:contentReference[oaicite:5]{index=5}
    print(f"[Stage2-vLLM] Loading vLLM LLM(model={args.model_name!r}, task='embed') ...")
    t0 = time.time()
    llm = LLM(
        model=args.model_name,
        task="embed",                   # 关键：声明这是 embedding 模型 :contentReference[oaicite:6]{index=6}
        tensor_parallel_size=args.tensor_parallel_size,
        dtype=args.dtype,
        gpu_memory_utilization=args.gpu_memory_utilization,
        trust_remote_code=args.trust_remote_code,
        enforce_eager=args.enforce_eager,
    )
    print(f"[Stage2-vLLM] vLLM model loaded in {time.time()-t0:.1f}s")

    # ---- 逐 row-group 流式读取 segments.parquet ----
    pf = pq.ParquetFile(str(segments_path))
    num_row_groups = pf.num_row_groups
    print(f"[Stage2-vLLM] segments.parquet has {num_row_groups} row groups")

    # 估计总 sentence 数量（用于进度条）
    total_rows_meta = None
    if pf.metadata is not None and pf.metadata.num_rows is not None:
        total_rows_meta = int(pf.metadata.num_rows)

    if args.max_segments > 0:
        if total_rows_meta is not None:
            total_for_pbar = min(total_rows_meta, args.max_segments)
        else:
            total_for_pbar = args.max_segments
    else:
        total_for_pbar = total_rows_meta  # 可能是 None
    
    writer = None
    n_rows_total = 0
    n_rows_encoded = 0
    t1 = time.time()

    # 主进度条：按 sentence 数量更新
    pbar = tqdm(
        total=total_for_pbar,
        desc="[Stage2-vLLM] Embedding sentences",
        unit="sent",
    )
    
    for rg_idx in range(num_row_groups):
        if args.max_segments > 0 and n_rows_encoded >= args.max_segments:
            print(f"[Stage2-vLLM] Reached max_segments={args.max_segments}, stop early.")
            break

        print(f"[Stage2-vLLM] Reading row group {rg_idx+1}/{num_row_groups} ...")
        # 只取我们需要的列，尽量节省内存
        table = pf.read_row_group(
            rg_idx,
            columns=["sample_idx", "section_idx", "sent_idx", "text"]
        )
        df = table.to_pandas()
        n_rows = len(df)
        n_rows_total += n_rows
        if n_rows == 0:
            continue

        # 根据 max_segments 可选截断当前 row-group
        if args.max_segments > 0:
            remain = args.max_segments - n_rows_encoded
            if remain <= 0:
                break
            if n_rows > remain:
                df = df.iloc[:remain].copy()
                n_rows = len(df)

        texts = df["text"].astype(str).tolist()

        # ---- 一次性把当前 row-group 的所有句子塞进 vLLM.embed ----
        print(f"[Stage2-vLLM] Calling llm.embed on {n_rows} sentences ...")
        t_rg = time.time()
        outputs = llm.embed(texts)  # 返回 list[EmbeddingRequestOutput]，顺序和输入一致:contentReference[oaicite:7]{index=7}
        if len(outputs) != n_rows:
            raise RuntimeError(
                f"Row group {rg_idx}: llm.embed returned {len(outputs)} items, "
                f"but input has {n_rows} sentences."
            )

        embs: List[List[float]] = []
        for out in outputs:
            emb_vec = extract_embedding_from_output(out)
            embs.append(emb_vec)
            n_rows_encoded += 1

        print(f"  [Stage2-vLLM] row_group={rg_idx+1}, rows={n_rows}, "
              f"encoded_so_far={n_rows_encoded}, time={time.time()-t_rg:.1f}s")

        # ---- 写出这一组的 embedding ----
        df_out = pd.DataFrame(
            {
                "sample_idx": df["sample_idx"].astype(np.int64),
                "section_idx": df["section_idx"].astype(np.int32),
                "sent_idx": df["sent_idx"].astype(np.int32),
                "emb": embs,
            }
        )

        table_out = pa.Table.from_pandas(df_out, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(
                str(emb_path),
                table_out.schema,
                compression="zstd",
                version="2.6",
            )
        writer.write_table(table_out)
        # 更新 sentence 级进度条（按照当前 row-group 实际编码的行数更新）
        pbar.update(len(df_out))
        if args.max_segments > 0 and n_rows_encoded >= args.max_segments:
            print(f"[Stage2-vLLM] Hit max_segments={args.max_segments}, stop after current row group.")
            break
    # 关闭进度条
    pbar.close()
    if writer is not None:
        writer.close()

    print(f"[Stage2-vLLM] Wrote embeddings: {emb_path}")
    print(f"[Stage2-vLLM] Total sentences seen={n_rows_total}, encoded={n_rows_encoded}, "
          f"time={time.time()-t1:.1f}s")

    meta = {
        "segments_path": str(segments_path),
        "embeddings_path": str(emb_path),
        "model_name": args.model_name,
        "tensor_parallel_size": args.tensor_parallel_size,
        "dtype": args.dtype,
        "gpu_memory_utilization": args.gpu_memory_utilization,
        "trust_remote_code": bool(args.trust_remote_code),
        "enforce_eager": bool(args.enforce_eager),
        "rows_total": int(n_rows_total),
        "rows_encoded": int(n_rows_encoded),
        "max_segments": int(args.max_segments),
        "build_time_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    with meta_path.open("w", encoding="utf-8") as f:
        json.dump(meta, f, ensure_ascii=False, indent=2)
    print(f"[Stage2-vLLM] Wrote meta: {meta_path}")

    print("[Stage2-vLLM Summary]")
    print(f"  rows_total     = {n_rows_total:,}")
    print(f"  rows_encoded   = {n_rows_encoded:,}")
    print(f"  embeddings.parquet = {emb_path}")

if __name__ == "__main__":
    main()
