#!/usr/bin/env bash
set -xeuo pipefail
RUNTIME_ENV="/remote-home1/yli/Workspace/BandPO/RLtraining/verl/recipe/dapo/runtime_env.yaml"
project_name="clip_improve"
exp_name="DapoMathDataset_qwen25_3B_trgppo_on_dapo_relax_bisect_nolog_kl005_rmax10" # no dual-clip, no clip higher
model_path="/remote-home1/yli/Workspace/BandPO/data/models/qwen25/base/Qwen2.5-3B"
CKPTS_DIR="/remote-home1/yli/Workspace/BandPO/data/ckpts/${project_name}/${exp_name}"
debug_record_path="/remote-home1/yli/Workspace/BandPO/data/records/${project_name}/${exp_name}/record.txt"
mkdir -p "$(dirname "$debug_record_path")"
: > "$debug_record_path"
# top_k 0 for HF rollout, -1 for vLLM rollout
max_prompt_length=$((1024 * 1))
max_response_length=$((1024 * 3))
overlong_buffer_len=$((1024 * 2))
actor_ppo_max_token_len=$((max_prompt_length + max_response_length))
infer_ppo_max_token_len=$((max_prompt_length + max_response_length))
max_num_batched_tokens=$((max_prompt_length + max_response_length))
train_batch_size=512 # 512
gen_prompt_bsz=$((train_batch_size * 3))
max_num_gen_batches=10
n_gpus_per_node=4 # 4
val_before_train=True # True
rollout_n=16 # 16
ppo_mini_batch_size=32
validate_n=1 # 实际上已经翻倍16，所以2的话实际是32
    # data.val_files="['$math_500_test', '$aime2024_test', '$aime2025_test', '$amc2023_test']" \
    # data.val_files="['$math_500_test', '$aime2024_16_test', '$aime2025_16_test', '$amc2023_16_test']" \
dapo_train=/remote-home1/yli/Workspace/BandPO/data/dataset/dapo/dapo-math-17k.parquet
dapo_train_processed=/remote-home1/yli/Workspace/BandPO/data/dataset/dapo_processed/modified/DAPO-Math-17k-Processed_modified.parquet
math_500_l35_train=/remote-home1/yli/Workspace/BandPO/data/dataset/math-500/train/train_L3-5.parquet

gsm8k_test=/remote-home1/yli/Workspace/BandPO/data/dataset/gsm8k/verl2dapo/test.parquet
math_500_test=/remote-home1/yli/Workspace/BandPO/data/dataset/math-500/test/test.parquet
math_test=/remote-home1/yli/Workspace/BandPO/data/dataset/math/verl2dapo/test/test.parquet
aime2024_test=/remote-home1/yli/Workspace/BandPO/data/dataset/aime2024_dapo/test.parquet
aime2024_16_test=/remote-home1/yli/Workspace/BandPO/data/dataset/aime2024_dapo/test_16_shuffle24.parquet
aime2025_test=/remote-home1/yli/Workspace/BandPO/data/dataset/aime2025_dapo/test.parquet
aime2025_16_test=/remote-home1/yli/Workspace/BandPO/data/dataset/aime2025_dapo/test_16_shuffle24.parquet
amc2023_test=/remote-home1/yli/Workspace/BandPO/data/dataset/amc2023_dapo/test.parquet
amc2023_16_test=/remote-home1/yli/Workspace/BandPO/data/dataset/amc2023_dapo/test_16_shuffle24.parquet

    # +actor_rollout_ref.actor.use_tokenwise_trust_region_mapping_clip=False \

ray job submit --no-wait --runtime-env="${RUNTIME_ENV}" \
    --working-dir "/remote-home1/yli/Workspace/BandPO/RLtraining/verl" \
    -- python3 -m recipe.dapo.main_dapo \
    data.train_files="['$dapo_train_processed', '$math_500_l35_train']" \
    data.val_files="['$math_500_test', '$aime2024_test', '$amc2023_test']" \
    data.prompt_key=prompt \
    data.truncation='left' \
    data.max_prompt_length=${max_prompt_length} \
    data.max_response_length=${max_response_length} \
    data.gen_batch_size=${gen_prompt_bsz} \
    data.train_batch_size=${train_batch_size} \
    actor_rollout_ref.rollout.n=${rollout_n} \
    algorithm.adv_estimator='grpo' \
    algorithm.use_kl_in_reward=False \
    algorithm.kl_ctrl.kl_coef=0.0 \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.actor.kl_loss_coef=0.0 \
    actor_rollout_ref.actor.clip_ratio_low=0.2 \
    actor_rollout_ref.actor.clip_ratio_high=0.28 \
    actor_rollout_ref.actor.clip_ratio_c=10.0 \
    +actor_rollout_ref.actor.clip_use_dual_clip=True \
    +actor_rollout_ref.actor.use_tokenwise_ratio_bounds=True \
    +actor_rollout_ref.actor.tokenwise_ratio_bounds_method="trgppo" \
    +actor_rollout_ref.actor.does_relax_high_p_bound=True \
    +actor_rollout_ref.actor.rmax=10.0 \
    +actor_rollout_ref.actor.trgppo_solve_method="bisect" \
    +actor_rollout_ref.actor.trgppo_use_log_domain=False \
    +actor_rollout_ref.actor.kl_delta=0.05 \
    +actor_rollout_ref.actor.delta_mapping_ratio_method="sub" \
    +actor_rollout_ref.actor.use_one_minus_p_for_mapping_in_div=True \
    +actor_rollout_ref.actor.mapping_eps=1e-12 \
    +actor_rollout_ref.actor.mapping_ratio_min_cap=1e-6 \
    +actor_rollout_ref.actor.mapping_ratio_max_cap=1e6 \
    +actor_rollout_ref.actor.is_debug=True \
    +actor_rollout_ref.actor.debug_record_path="${debug_record_path}" \
    +actor_rollout_ref.actor.debug_clip_print_max_pairs=256 \
    algorithm.filter_groups.enable=True \
    algorithm.filter_groups.max_num_gen_batches=${max_num_gen_batches} \
    algorithm.filter_groups.metric=acc \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=True \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=True \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=${actor_ppo_max_token_len} \
    actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=${infer_ppo_max_token_len} \
    actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=${infer_ppo_max_token_len} \
    actor_rollout_ref.model.path="${model_path}" \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.optim.lr_warmup_steps=10 \
    actor_rollout_ref.actor.optim.weight_decay=0.1 \
    actor_rollout_ref.actor.ppo_mini_batch_size=${ppo_mini_batch_size} \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True\
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.grad_clip=1.0 \
    actor_rollout_ref.actor.loss_agg_mode="token-mean" \
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=1 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.80 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.enable_chunked_prefill=True \
    actor_rollout_ref.rollout.max_num_batched_tokens=${max_num_batched_tokens} \
    actor_rollout_ref.rollout.temperature=1.0 \
    actor_rollout_ref.rollout.top_p=1.0 \
    actor_rollout_ref.rollout.top_k=-1  \
    actor_rollout_ref.rollout.val_kwargs.temperature=1.0 \
    actor_rollout_ref.rollout.val_kwargs.top_p=1.0 \
    actor_rollout_ref.rollout.val_kwargs.top_k=-1 \
    actor_rollout_ref.rollout.val_kwargs.do_sample=True \
    actor_rollout_ref.rollout.val_kwargs.n=${validate_n} \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.ref.ulysses_sequence_parallel_size=1 \
    actor_rollout_ref.actor.fsdp_config.fsdp_size=-1 \
    reward_model.reward_manager=dapo \
    reward_model.overlong_buffer.enable=True \
    reward_model.overlong_buffer.len=${overlong_buffer_len} \
    reward_model.overlong_buffer.penalty_factor=1.0 \
    trainer.logger='["console","wandb"]' \
    trainer.project_name="${project_name}" \
    trainer.experiment_name="${exp_name}" \
    trainer.n_gpus_per_node=${n_gpus_per_node} \
    trainer.nnodes=1 \
    trainer.val_before_train=${val_before_train} \
    trainer.test_freq=4 \
    trainer.save_freq=8 \
    trainer.total_epochs=12 \
    trainer.default_local_dir="${CKPTS_DIR}" \
    trainer.resume_mode=auto
